name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  format:
    name: Format
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Format
        run: npm run format:check
        shell: bash

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Lint
        run: npm run lint
        shell: bash

  type-check:
    name: Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Type Check
        run: npm run type-check
        shell: bash

  build-ios:
    name: Build iOS
    runs-on: macos-26
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Build iOS
        run: npx expo run:ios --configuration Release --device generic
        shell: bash

  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v7
        with:
          node-version-file: .nvmrc
          cache: npm

      - name: Install Dependencies
        run: npm ci
        shell: bash

      - name: Prebuild Android
        run: npx expo prebuild --platform android
        shell: bash

      - name: Setup Java
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Build Android
        run: cd android && ./gradlew app:bundleRelease
        shell: bash
